language: c

compiler:
    - gcc

before_script:
    - git clone --depth 1 https://github.com/antirez/redis.git
    - sudo make -C redis install
    - sudo apt-get -qq update
    - sudo pip install redis ramp-packer
    - sudo pip install git+https://github.com/mnunberg/rmtest

script:
    - make
    - make test
    - cd tests && python pytests.py

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    skip_cleanup: true
    acl: public_read
    bucket: redismodules
    upload-dir: rebloom
    on:
        branch: master
    local_dir: $TRAVIS_BUILD_DIR/build
