site_name: ReBloom Documentation
repo_url: https://github.com/RedisLabsModules/rebloom
theme: material

markdown_extensions:
  - codehilite
  - toc(permalink=true)
 
pages:
    - 'ReBloom': 'index.md'
    - 'Commands': 'Commands.md'       
